-- 1. Tabel Kategori (Master Data)
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('income', 'expense')), 
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 2. Tabel Transaksi
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  date DATE DEFAULT CURRENT_DATE,
  amount DECIMAL(12,2) NOT NULL,
  description TEXT,
  type TEXT CHECK (type IN ('income', 'expense')),
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 3. Aktifkan Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- 4. Kebijakan Keamanan (Policies) untuk Kategori
CREATE POLICY "Users can manage their own categories" 
ON categories FOR ALL USING (auth.uid() = user_id);

-- 5. Kebijakan Keamanan (Policies) untuk Transaksi
CREATE POLICY "Users can manage their own transactions" 
ON transactions FOR ALL USING (auth.uid() = user_id);

-- 6. Insert Kategori Default (Opsional)
-- Karena user_id null di sini, kategori ini biasanya tidak muncul jika RLS aktif.
-- User disarankan menambah kategori sendiri lewat CategoryManager.